### PR TITLE
Completed working version of `executor`

### PR DESCRIPTION
**Pull request by sogko**
### Details
- Ported `executor` from `graphql-js`
- Did not fully implement ability to resolve fields from promises
  - Might explore ways to resolve fields using go-routines and channels (a close equivalent and probable valid use-case i.e. async data fetching)
- Implemented most of the graphql types (`types/*,go`)
  - Introspection schema definition
  - Scalar definitions (`GraphQLString`, `GraphQLInt` etc)
  - But still some way to go before completion (implementation & tests)
- Initialization loop problem with schema definition (`executor/introspection.go`)
       - ie `__Type has __Type` or `__Type has __InputValue has  __Type` etc (cyclic reference)
       - Golang don't like initialization loop during compile time.
         So we can't define schema like this:
```javascript
// pseudo-golang
__Type = {
  name:  "__Type",
  fields: [
    ...
    ofType: {
      type: __Type //<-- __Type has __Type
    }
  ],
}
```
To work around that,
```javascript 
__Type = {
  name:  "__Type",
  fields: [
    ...
    ofType: {}, // defer `ofType` field config to later
  ],
}
...
// add `ofType` field config to __Type
// using AddFieldConfig(fieldName, fieldConfig)
__Type.AddFieldConfig("ofType", {
  Type: __Type,
})
__
```
- Porting `executor` tests from `graphql-js/src/execution/__tests__/*.js`
    - [x] executor
    - [x] abstract
    - [x] directives)
    - [x] executor_schema
    - [x] lists
    - [x] mutation
    - [x] nonnull
    - [x] union-interface
    - [x] variables

- Enabled `graphql_test.go` tests (StarWars test)
 - All passed
 - Useful to look at how schema are defined and the structure of the result object returned.
 
### Tests
```bash
$ go build
$ go test ./...
ok  	github.com/chris-ramon/graphql-go	0.007s
?   	github.com/chris-ramon/graphql-go/debug	[no test files]
?   	github.com/chris-ramon/graphql-go/errors	[no test files]
ok  	github.com/chris-ramon/graphql-go/executor	0.017s
?   	github.com/chris-ramon/graphql-go/language/ast	[no test files]
?   	github.com/chris-ramon/graphql-go/language/kinds	[no test files]
ok  	github.com/chris-ramon/graphql-go/language/lexer	0.010s
?   	github.com/chris-ramon/graphql-go/language/location	[no test files]
ok  	github.com/chris-ramon/graphql-go/language/parser	0.019s
?   	github.com/chris-ramon/graphql-go/language/source	[no test files]
?   	github.com/chris-ramon/graphql-go/testutil	[no test files]
ok  	github.com/chris-ramon/graphql-go/types	0.006s
?   	github.com/chris-ramon/graphql-go/validator	[no test files]
```

### CODE REVIEW

**Comment by sogko** [comment]
Completed porting all `executor` tests from `graphql-js`

Will be working on `visitor` and `printer` next on another PR because some tests depend on them (currently marked as skipped)

**Comment by chris-ramon** [comment]
Thanks for great work on `executor` @sogko, I will go ahead and merge this one followed but the `visitor` and `printer`, def looks good to me, I think we can work on todos and resolving fields with `goroutines` in new pr's.

**Comment by sogko** [comment]
Awesome, thanks for taking your time to look at these PRs 👍🏻

In addition to clearing up the TODOs and exploring the use of go-routines for async data fetching,
the `types` package currently requires some more tests + fixes + code clean up as well.

Btw, I've started work on getting a `graphql-relay-js` port at https://github.com/sogko/graphql-relay-go
Feel free to comment and any feedback would be appreciated.

**Comment by chris-ramon** [comment]
Alright, def ill take a look to `graphql-relay-go`, and I've saw ur working on `types` branch, I am wondering what would you work next? I have not look in deep of what are missing to port yet.

I am working on making test's pass that was omit with `t.Skipf` in 
`graphql-go/executor/nonnull_test.go`.

**Comment by sogko** [comment]
Currently the `types` branch includes some fixes to bugs where introspection does not return the right output when queried (Some of the fixes I've yet to commit to the branch yet).

I guess I'll work on the porting the tests for `types` next. Currently only `serialization.js`/`scalars_serialization_test.go` is complete, the following have yet to be ported fully:
- `graphlql-js/src/type/__tests__/definition.js`
- `graphlql-js/src/type/__tests__/enumType.js`
- `graphlql-js/src/type/__tests__/introspection.js`
- `graphlql-js/src/type/__tests__/validation.js`

**Comment by chris-ramon** [comment]
Awesome!, thanks for status update! :star2: hopefully we will hit v0.1 soon :rocket:.

**Pull request merged**
