### PR TITLE
Completed implementation/port of `ast`, based on `graphql-js`

### PR DESCRIPTION
**Pull request by sogko**
Hi @chris-ramon 

This PR is built on top of the previous PR (PR #2 ). It might be easier to look and complete PR #2 first before considering merging this.

### Details
- Struct and interface definitions are based on `graphql-js/src/language/ast.js`
- The following interfaces are defined:
```go
type Node interface{}
type Definition interface{}
type TypeDefintion interface{}
type Selection interface{}
type Type interface{}
type Value interface{}
```
- Structs that are expected to implement an interface are enforced on compile-time, for e.g:
```go
var _ Value = (*Variable)(nil)
var _ Value = (*IntValue)(nil)
var _ Value = (*FloatValue)(nil)
...
```
- Each AST type implementation has a corresponding `New()`-style constructors to correctly initialise `Kind` property.
- All structs property uses references wherever possible for efficiency. It also makes the library more consistent
- For discussion:
 - Each AST type definition has been separated into individual files. Any comments on the file name convention? It might seem that there are too many files. 
  This is an alternative to writing all of the implementation is one huge `ast.go` file, which I imagined it would be harder to maintain in the long run.

### Tests
```bash
$ go build
$ go test ./...
ok  	github.com/chris-ramon/graphql-go	0.006s
?   	github.com/chris-ramon/graphql-go/debug	[no test files]
?   	github.com/chris-ramon/graphql-go/errors	[no test files]
?   	github.com/chris-ramon/graphql-go/executor	[no test files]
?   	github.com/chris-ramon/graphql-go/language/ast	[no test files]
?   	github.com/chris-ramon/graphql-go/language/kinds	[no test files]
ok  	github.com/chris-ramon/graphql-go/language/lexer	0.008s
?   	github.com/chris-ramon/graphql-go/language/location	[no test files]
ok  	github.com/chris-ramon/graphql-go/language/parser	0.016s
?   	github.com/chris-ramon/graphql-go/language/source	[no test files]
?   	github.com/chris-ramon/graphql-go/testutil	[no test files]
?   	github.com/chris-ramon/graphql-go/types	[no test files]
?   	github.com/chris-ramon/graphql-go/validator	[no test files]
```

### CODE REVIEW

**Comment by chris-ramon** [comment]
Thanks so much for you work on this @sogko :clap: :star: 

In regards the file naming for `ast` package, what do you think about this file structure:

```
ast/
  location.go
  node.go
  name.go
  document.go
  definitions.go
  selections.go
  arguments.go
  values.go
  directives.go
  types.go
  type_definitions.go
```

ast/location.go
 - `type Location struct`

ast/node.go
  - `type Node interface`

ast/name.go
  - `type Name struct`

ast/document.go
 - `type Document struct`

ast/definitions.go:
 - `type Definition interface`
 - `type OperationDefinition  struct`
 - `type FragmentDefinition  struct`
 - `type VariableDefinition  struct`

ast/selections.go:
 - `type Selection interface`
 - `type Field  struct`
 - `type FragmentSpread  struct`
 - `type InlineFragment  struct`
 - `type SelectionSet  struct`

ast/arguments.go
 - `type Argument struct`

ast/values.go
 - `type Value interface`
 - `type Variable  struct`
 - `type IntValue  struct`
 - `type FloatValue  struct`
 - `type StringValue  struct`
 - `type BooleanValue  struct`
 - `type EnumValue  struct`
 - `type ListValue  struct`
 - `type ObjectValue  struct`
 - `type ObjectField struct`

ast/directives.go
 - `type Directive struct`

ast/types.go
 - `type Type interface`
 - `type NamedType  struct`
 - `type ListType  struct`
 - `type NonNullType  struct`

ast/type_definitions.go
 - `type TypeDefinition interface`
 - `type ObjectTypeDefinition  struct`
 - `type FieldDefinition struct`
 - `type InputValueDefinition  struct`
 - `type InterfaceTypeDefinition  struct`
 - `type UnionTypeDefinition  struct`
 - `type ScalarTypeDefinition  struct`
 - `type EnumTypeDefinition  struct`
 - `type EnumValueDefinition struct`
 - `type InputObjectTypeDefinition  struct`
 - `type TypeExtensionDefinition  struct`

**Comment by sogko** [comment]
Awesome! I think thats a pretty good balance between having all in one huge file vs individual files for each struct. 👍🏻

I'll make the change and push it soon.

Thanks again!

**Comment by sogko** [comment]
I've made the changes re-organize `ast` files.

In addition to that, I've fixed an error in `graphQLError` I stumbled upon while starting work on `executor`.

Thanks again!

**Comment by chris-ramon** [comment]
Yup I agree we have it in a good balance, by now is good with this file structure, the longest file contains about ~410 loc which is not that bad considering that those files contains just interfaces and structs with methods that just fulfill interface contracts.

Thanks a lot for the updates! :+1: looks good.

**Pull request merged**
