### PR TITLE
Port the rest of the `types` package tests

### PR DESCRIPTION
**Pull request by sogko**
### Details
Currently the types branch includes some fixes to bugs where introspection does not return the right output when queried (Some of the fixes I've yet to commit to the branch yet).

This PR would not be ready for merge until all tests in the task lists are completed and all tests have passed.

### Task list
- [x] scalars_serialization tests
- [x] definition tests
- [x] enumType tests
- [x] introspection tests
- [x] validation tests
- [x] code cleanup

### Test
```go
$ go build && go test ./...
ok  	github.com/chris-ramon/graphql-go	0.014s
?   	github.com/chris-ramon/graphql-go/errors	[no test files]
ok  	github.com/chris-ramon/graphql-go/executor	0.110s
?   	github.com/chris-ramon/graphql-go/language/ast	[no test files]
?   	github.com/chris-ramon/graphql-go/language/kinds	[no test files]
ok  	github.com/chris-ramon/graphql-go/language/lexer	0.011s
?   	github.com/chris-ramon/graphql-go/language/location	[no test files]
ok  	github.com/chris-ramon/graphql-go/language/parser	0.039s
ok  	github.com/chris-ramon/graphql-go/language/printer	0.055s
?   	github.com/chris-ramon/graphql-go/language/source	[no test files]
ok  	github.com/chris-ramon/graphql-go/language/visitor	0.017s
ok  	github.com/chris-ramon/graphql-go/testutil	0.035s
ok  	github.com/chris-ramon/graphql-go/types	0.098s
?   	github.com/chris-ramon/graphql-go/validator	[no test files]
```

### CODE REVIEW

**Comment by sogko** [comment]
Completed porting tests for `types`. Adding tests cases did exposed more missing implementation and bugs.

**Notes**
- This might conflict with PR #16, a lot of changes were made to `types` package directory.
- TODO in a separate PR: Consolidate a couple of common utility/helpers e.g `executor.isNullish()` 
- Added a test util to check if a `map[string]interface{}` is a subset of another map (`testutil.ContainSubset()`). Needed for `introspection_test.go`
- Added a test util to check if a `[]interface{}` is a subset of another slice (`testutil.ContainSubsetSlice()`). Needed for `introspection_test.go`

/cc @chris-ramon

**Comment by chris-ramon** [comment]
Thanks a lot! for ur work on this one :star2: finally landed :smile:

**Comment by sogko** [comment]
Haha no problem, was glad to contribute 👍🏻
I just wanted to quickly see a working implementation of graphql for golang as quickly as possible (I was getting kind of jealous that ruby, python, scala etc already have working libraries for graphql)

By the way, I've got a live demo of `graphql-go`, using relay, graphiql and all that goodness, up and running at http://bit.ly/try-graphql-go
The source is available at https://github.com/sogko/golang-graphql-playground

Cheers!

**Comment by chris-ramon** [comment]
That is so awesome! :+1: great example, def will take a look closely.

**Pull request merged**
