### PR TITLE
Update the README.md to be more informative

### PR DESCRIPTION
**Pull request by EmergentBehavior**
Expand README.md so people coming to the project for the first time have a better idea of what's going on. Props to @sogko for much of the info here.

### CODE REVIEW

**Comment by sogko** [comment]
This looks great! Thanks @EmergentBehavior 

This PR is based on the discussions in issue #29 

I have a couple of suggestions:
- Typo in "by the `lastest` formal GraphQL specification", probably should be `latest`.
- Can I suggest adding the link to GraphQL spec releases https://github.com/facebook/graphql/releases somewhere? It'll help with newcomers knowing where they can find them.

Thanks again!

/cc @chris-ramon

**Comment by EmergentBehavior** [comment]
@sogko Fixing and updating now.

**Comment by chris-ramon** [comment]
Awesome!, thanks for working on this :star2: - really appreciate it, would like to point out:

- In latest porting [pr](https://github.com/chris-ramon/graphql-go/pull/19) from my side I was using `graphql-js` - `v0.4.7`, since there are notable [diff](https://github.com/graphql/graphql-js/compare/v0.4.3...v0.4.7) between both releases, I think we are fine showing on `README` that current `graphql-js` version ported is: `v0.4.3`, after merging this one #30, and perhaps other pr's related to package/files re-organization, I think we are ready to keep going.

- I've quick reviewed and yes, we are good marking `printer`, `schema printer`, `visitor` and `executor` as done, I've found just two things to update/fix (pull requests are welcome):
  - Port this test: https://github.com/graphql/graphql-js/blob/v0.4.2/src/language/__tests__/visitor.js#L124
  - Rename `TestUsesTheMutationSchemaForQueries `-> `TestUsesTheMutationSchemaForMutations` - https://github.com/chris-ramon/graphql-go/blob/master/executor/executor_test.go#L669

Besides that, we are good to merge this one, thanks again! :+1: 

cc/ @sogko

**Comment by EmergentBehavior** [comment]
Cool! Can look at those issues, maybe submit separate PRs unless someone else jumps on it first.

**Comment by EmergentBehavior** [comment]
Added them to this PR but can hold them for another one if you'd like.

**Comment by sogko** [comment]
Hi @EmergentBehavior 

Thanks for picking up the work to for porting those additional tests that @chris-ramon pointed out.

But may I suggest we have it in a separate PR? I foresee it's going to conflict greatly with PR #30 which is pretty huge.

I would love to have this README.md merged soon though 👍🏻

**Comment by EmergentBehavior** [comment]
@sogko No problemo -- will split them up.

**Comment by EmergentBehavior** [comment]
@sogko @chris-ramon Things got a bit mucked so I'm going to close the two PRs I have open and properly submit each change from a different branch.

**Pull request closed without merging**
